component_depth: 1
languages:
- java
exclude:
- ./lib/.*
- ./native/.*
- ./native/linux/.*
- ./native/linux/lib/.*
- ./native/win32/.*
- ./native/win32/lib/.*
- ./plugins/.*
- ./plugins/org.columba.chat.altura/.*
- ./plugins/org.columba.chat.altura/api/.*
- ./plugins/org.columba.chat.altura/api/org/.*
- ./plugins/org.columba.chat.altura/api/org/columba/.*
- ./plugins/org.columba.chat.altura/api/org/columba/chat/.*
- ./plugins/org.columba.chat.altura/api/org/columba/chat/api/.*
- ./plugins/org.columba.chat.altura/build/.*
- ./plugins/org.columba.chat.altura/build/org/.*
- ./plugins/org.columba.chat.altura/build/org/columba/.*
- ./plugins/org.columba.chat.altura/build/org/columba/chat/.*
- ./plugins/org.columba.chat.altura/build/org/columba/chat/action/.*
- ./plugins/org.columba.chat.altura/build/org/columba/chat/images/.*
- ./plugins/org.columba.chat.altura/lib/.*
- ./plugins/org.columba.chat.altura/res/.*
- ./plugins/org.columba.chat.altura/res/org/.*
- ./plugins/org.columba.chat.altura/res/org/columba/.*
- ./plugins/org.columba.chat.altura/res/org/columba/chat/.*
- ./plugins/org.columba.chat.altura/res/org/columba/chat/action/.*
- ./plugins/org.columba.chat.altura/res/org/columba/chat/images/.*
- ./plugins/org.columba.core.HippoLookAndFeel/.*
- ./plugins/org.columba.core.HippoLookAndFeel/lib/.*
- ./plugins/org.columba.core.KunststoffLookAndFeel/.*
- ./plugins/org.columba.core.KunststoffLookAndFeel/lib/.*
- ./plugins/org.columba.core.LiquidLookAndFeel/.*
- ./plugins/org.columba.core.LiquidLookAndFeel/lib/.*
- ./plugins/org.columba.core.LogDisplay/.*
- ./plugins/org.columba.core.MetouiaLookAndFeel/.*
- ./plugins/org.columba.core.MetouiaLookAndFeel/lib/.*
- ./plugins/org.columba.core.WinLAFLookAndFeel/.*
- ./plugins/org.columba.core.WinLAFLookAndFeel/lib/.*
- ./plugins/org.columba.example.CSVAddressbookImportFilter/.*
- ./plugins/org.columba.example.ConfigExample/.*
- ./plugins/org.columba.example.HelloWorldAction/.*
- ./plugins/org.columba.example.MBOXMailImportFilter/.*
- ./plugins/org.columba.example.groovy.HelloWorldAction/.*
- ./plugins/org.columba.mail.EudoraMailImportFilter/.*
- ./plugins/org.columba.mail.PlaySoundFilterAction/.*
- ./plugins/org.columba.mail.ToOrCcFilter/.*
- ./res/.*
- ./res/org/.*
- ./res/org/columba/.*
- ./res/org/columba/addressbook/.*
- ./res/org/columba/addressbook/action/.*
- ./res/org/columba/addressbook/config/.*
- ./res/org/columba/addressbook/i18n/.*
- ./res/org/columba/addressbook/i18n/dialog/.*
- ./res/org/columba/addressbook/i18n/global/.*
- ./res/org/columba/addressbook/i18n/header/.*
- ./res/org/columba/addressbook/i18n/menu/.*
- ./res/org/columba/addressbook/i18n/tree/.*
- ./res/org/columba/addressbook/parser/.*
- ./res/org/columba/addressbook/plugin/.*
- ./res/org/columba/core/.*
- ./res/org/columba/core/action/.*
- ./res/org/columba/core/config/.*
- ./res/org/columba/core/i18n/.*
- ./res/org/columba/core/i18n/dialog/.*
- ./res/org/columba/core/i18n/global/.*
- ./res/org/columba/core/images/.*
- ./res/org/columba/core/images/mime/.*
- ./res/org/columba/core/plugin/.*
- ./res/org/columba/mail/.*
- ./res/org/columba/mail/action/.*
- ./res/org/columba/mail/config/.*
- ./res/org/columba/mail/folder/.*
- ./res/org/columba/mail/i18n/.*
- ./res/org/columba/mail/i18n/dialog/.*
- ./res/org/columba/mail/i18n/filter/.*
- ./res/org/columba/mail/i18n/global/.*
- ./res/org/columba/mail/i18n/header/.*
- ./res/org/columba/mail/i18n/menu/.*
- ./res/org/columba/mail/i18n/statusbar/.*
- ./res/org/columba/mail/i18n/tree/.*
- ./res/org/columba/mail/plugin/.*
- ./res/org/columba/mail/sound/.*
